# Generated by Django 5.2.2 on 2025-06-09 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spot', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('r_room', "Rohan's Room"), ('R_room', "Radhika's Room"), ('P_room', "Parents' Room"), ('G_room', 'Guest Room'), ('Rr_bathroom', 'R & r Bathroom'), ('P_bathroom', "Parents' Bathroom"), ('C_bathroom', 'Corridor Bathroom'), ('G_bathroom', 'Guest Bathroom'), ('living_room', 'Living Room'), ('kitchen', 'Kitchen')], max_length=100)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
