# Generated by Django 5.2.2 on 2025-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
